### PR TITLE
upgrade to v8 7.4.288.28

### LINKED ISSUE #340: array spread will crash the server process
```
do $$ 
  Object.prototype[Symbol.iterator] = function() {
     return {
       next:() => this
     }
  };
  [...({})]; 
$$ language plv8
```
fixed here: https://github.com/v8/v8/commit/1c48d52bb1ee9bb28e146c60eda08cd4afaa5745

### PR DESCRIPTION
**Pull request by pkit**
partially fixes #340

### CODE REVIEW

**Comment by pkit** [comment]
1. There's some inconsistent space/tab handling, converted to tabs
2. Should pass tests

**Comment by pkit** [comment]
Needs g++ >=4.9 and there is 4.8 in travis

**Comment by pkit** [comment]
Okay, I give up fighting with the Travis bullshit :)

**Comment by JerrySievert** [comment]
great work and thank you!

I'll pull this in locally and see if I can get travis working.

at some point, I need to run a formatter on the code anyways.

**Comment by JerrySievert** [comment]
I'm getting closer: https://travis-ci.org/JerrySievert/plv8/jobs/535016614

looks like `binutils` is too old now.

**Comment by pkit** [comment]
Okay, closing it

**Pull request closed without merging**
