### PR TITLE
Update BUILDING.md

### PR DESCRIPTION
**Pull request by asah**

### CODE REVIEW

**Comment by JerrySievert** [comment]
do you want to keep this open for any additional changes, or go ahead and have it merged?

**Comment by asah** [comment]
trivial: up to you.

**Comment by JerrySievert** [comment]
I’ll leave it open for a few days, just in case.

**Comment by JerrySievert** [comment]
fyi, releases are automatic via GitHub tagging - I'm ok automating the latest version creation, but some people try to match specific versions.

**Pull request merged**
