### PR TITLE
fix SPI not showing correct results sometimes

### LINKED ISSUE #133: plv8 does not handle SHOW statement correctly
``` sql
create extension if not exists plv8;
set custom.param = 'custom value';
do $$
  var param = plv8.execute('show custom.param')
  var all = plv8.execute('show all')
  plv8.elog(NOTICE, param, typeof param)
  plv8.elog(NOTICE, all, typeof all)
$$ language plv8;
```

output:

``` sh
NOTICE:  1 number
NOTICE:  241 number
```

It seems that it just returns number of rows returned from SHOW statement.

### LINKED ISSUE #135: plv8.execute  "EXPLAIN ..."
Looks like plv8.execute does not play with `EXPLAIN`  queries, and returns number but not result.

``` sql
DO $$ 
plv8.elog(NOTICE, 
  plv8.execute("EXPLAIN (ANALYZE, FORMAT JSON) SELECT * from sometable")
) 
$$ LANGUAGE plv8;
```

prints some number, not query plan

### PR DESCRIPTION
**Pull request by pkit**
SPI was not treating UTILITY and REWRITE results correctly

fixes #135
fixes #133

### CODE REVIEW

**Comment by pkit** [comment]
Can be probably backported to 2.x

**Comment by JerrySievert** [comment]
awesome!  but it appears it is breaking in 9.4 and 9.2 - likely just needs an alternate `expected`

**Comment by pkit** [comment]
@JerrySievert yup, added another one

**Comment by JerrySievert** [comment]
awesome, merged.  I'll do a backport soon, I have another to backport at the same time.

**Pull request merged**
