### PR TITLE
chore: add external utilities docs

### PR DESCRIPTION
**Pull request by divyenduz**
Related https://github.com/plv8/plv8/issues/446

### CODE REVIEW

**Comment by divyenduz** [comment]
@JerrySievert Does this match your expectations from #446? I wasn't sure where to put it so I made a new section but let me know if you rather want me to put it elsewhere or drop it completely 👍🏼

**Comment by JerrySievert** [comment]
I haven’t had a chance to review yet, unfortunately. I will try to get to it before the end of this weekend.

**Comment by divyenduz** [comment]
Thank you, sure, no hurries at all, please take your time :)

**Comment by JerrySievert** [comment]
awesome, thanks much!  I'll get this merged into the https://plv8.github.io/ documentation in just a few minutes!

**Pull request merged**
