### PR TITLE
Allocate FunctionCallInfo on the stack.

### PR DESCRIPTION
**Pull request by jeffcoat**
FunctionCallInfoData is defined differently
for PG_VERSION_NUM >= 120000; use a macro
from fmgr.h to initialize it.

### CODE REVIEW

**Comment by jeffcoat** [comment]
Whichever PR goes second can get the change to `.travis.yml` to add the `PGVERSION=12` environment.

**Comment by JerrySievert** [comment]
I'd rather see the change too `.travis.yml` in the other PR (which can go first), then can look at this one again.

thanks!

**Comment by JerrySievert** [comment]
can you do me a favor and update from upstream so that CI catches the other merged PR?

**Comment by jeffcoat** [comment]
Happy to. Thanks for your work maintaining this project.

**Pull request merged**
