### PR TITLE
Makefile.shared: don't install versioned module

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by JerrySievert** [comment]
is there some reason why you want to get rid of all versioning for modules for plv8?

**Comment by praiskup** [comment]
Uh, sorry, it's just non-standard thing;  and it broke our specfile (that can be fixed on our side).  Do we need the version string in so file?

**Comment by JerrySievert** [comment]
```
/usr/local/lib/postgresql/postgis-2.4.so
/usr/local/lib/postgresql/postgis-2.5.so
/usr/local/lib/postgresql/rtpostgis-2.5.so
/usr/local/lib/postgresql/postgis_topology-2.4.so
/usr/local/lib/postgresql/postgis_topology-2.5.so
/usr/local/lib/postgresql/rtpostgis-2.4.so
```

seems to have become a de facto standard for complicated modules that rely on other code that has braking changes between versions.

**Comment by JerrySievert** [comment]
fyi, change also breaks plv8 completely - see the travis checks.

**Comment by praiskup** [comment]
Nope, postgis is the only exception I'm aware of (all those you cited are from postgis);  and as such it complicated Fedora distro upgrades (and following `pg_upgrade`) a lot.   Now I finally worked-around that (by building the so file 3x, twice against new server, once against old server).

**Comment by praiskup** [comment]
Just try to google for the "pg_upgrade" and "postgis" headaches.  Definitely not a standard :-).

> fyi, change also breaks plv8 completely - see the travis checks.

To the topic -- I'd try to fix the travis if the change is otherwise acceptable...

**Pull request closed without merging**
