### PR TITLE
check tools; restartable build

### PR DESCRIPTION
**Pull request by asah**
build succeeds on ubuntu 18 / pg11 (I'll spare you the output).  You can now hit ctrl-C at any time and it cleans up & restarts correctly, without requiring you to restart the whole long build from scratch.

Harsh criticism is fine - this is my first PR to your repo, and have no expectations that you'll like my code esp in Makefile/shell :-)

This is only tested on Ubuntu 18.04.

**installation seems to work**

```
$ sudo make install
echo

cd /home/asah/plv8-2.3.9/build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
ninja: no work to do.
mkdir -p upgrade
./generate_upgrade.sh 2.3.9
/bin/mkdir -p '/usr/lib/postgresql/11/lib'
/bin/mkdir -p '/usr/share/postgresql/11/extension'
/bin/mkdir -p '/usr/share/postgresql/11/extension'
/usr/bin/install -c -m 755  plv8-2.3.9.so '/usr/lib/postgresql/11/lib/plv8-2.3.9.so'
/usr/bin/install -c -m 644 .//plv8.control '/usr/share/postgresql/11/extension/'
/usr/bin/install -c -m 644 .//plv8.control .//plv8--2.3.9.sql .//upgrade/plv8--1.5.0--2.3.9.sql .//upgrade/plv8--2.3.3--2.3.9.sql .//upgrade/plv8--2.0.0--2.3.9.sql .//upgrade/plv8--2.0.3--2.3.9.sql .//upgrade/plv8--1.5.3--2.3.9.sql .//upgrade/plv8--2.3.4--2.3.9.sql .//upgrade/plv8--2.3.1--2.3.9.sql .//upgrade/plv8--1.5.4--2.3.9.sql .//upgrade/plv8--1.5.1--2.3.9.sql .//upgrade/plv8--2.3.7--2.3.9.sql .//upgrade/plv8--2.3.0--2.3.9.sql .//upgrade/plv8--2.3.5--2.3.9.sql .//upgrade/plv8--2.3.2--2.3.9.sql .//upgrade/plv8--1.5.5--2.3.9.sql .//upgrade/plv8--1.5.2--2.3.9.sql .//upgrade/plv8--2.3.6--2.3.9.sql .//upgrade/plv8--2.1.0--2.3.9.sql .//upgrade/plv8--2.0.1--2.3.9.sql .//upgrade/plv8--2.3.8--2.3.9.sql .//upgrade/plv8--1.5.7--2.3.9.sql .//upgrade/plv8--1.5.6--2.3.9.sql .//plcoffee.control .//plcoffee--2.3.9.sql .//plls.control .//plls--2.3.9.sql  '/usr/share/postgresql/11/extension/'
/bin/mkdir -p '/usr/lib/postgresql/11/lib/bitcode/plv8-2.3.9'
/bin/mkdir -p '/usr/lib/postgresql/11/lib/bitcode'/plv8-2.3.9/
/usr/bin/install -c -m 644 plv8.bc '/usr/lib/postgresql/11/lib/bitcode'/plv8-2.3.9/./
/usr/bin/install -c -m 644 plv8_type.bc '/usr/lib/postgresql/11/lib/bitcode'/plv8-2.3.9/./
/usr/bin/install -c -m 644 plv8_func.bc '/usr/lib/postgresql/11/lib/bitcode'/plv8-2.3.9/./
/usr/bin/install -c -m 644 plv8_param.bc '/usr/lib/postgresql/11/lib/bitcode'/plv8-2.3.9/./
/usr/bin/install -c -m 644 coffee-script.bc '/usr/lib/postgresql/11/lib/bitcode'/plv8-2.3.9/./
/usr/bin/install -c -m 644 livescript.bc '/usr/lib/postgresql/11/lib/bitcode'/plv8-2.3.9/./
cd '/usr/lib/postgresql/11/lib/bitcode' && /usr/lib/llvm-6.0/bin/llvm-lto -thinlto -thinlto-action=thinlink -o plv8-2.3.9.index.bc plv8-2.3.9/plv8.bc plv8-2.3.9/plv8_type.bc plv8-2.3.9/plv8_func.bc plv8-2.3.9/plv8_param.bc plv8-2.3.9/coffee-script.bc plv8-2.3.9/livescript.bc
asah@dev-asah-east4-4cpu-2:~/plv8-2.3.9$ sudo su - postgres -c psql
psql (11.2 (Ubuntu 11.2-1.pgdg18.04+1))
Type "help" for help.

postgres=# create extension plv8;
CREATE EXTENSION
postgres=# SELECT plv8_version();
 plv8_version
--------------
 2.3.9
(1 row)
```

**self-tests seem to pass**

```
$ sudo su postgres -c "make installcheck"
/usr/lib/postgresql/11/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/11/bin'    --dbname=contrib_regression init-extension plv8 plv8-errors inline json startup_pre startup varparam json_conv jsonb_conv window guc es6 arraybuffer composites currentresource startup_perms bytea dialect
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test init-extension               ... ok
test plv8                         ... ok
test plv8-errors                  ... ok
test inline                       ... ok
test json                         ... ok
test startup_pre                  ... ok
test startup                      ... ok
test varparam                     ... ok
test json_conv                    ... ok
test jsonb_conv                   ... ok
test window                       ... ok
test guc                          ... ok
test es6                          ... ok
test arraybuffer                  ... ok
test composites                   ... ok
test currentresource              ... ok
test startup_perms                ... ok
test bytea                        ... ok
test dialect                      ... ok

======================
 All 19 tests passed.
======================
```

### CODE REVIEW

**Comment by asah** [comment]
looks like travis stalled after 43mins on pg 9.2... which seems quite long... I wonder if we can share/cache some of the CI process?  also, do we care about older versions of pg? should we test pg 10 and 11 ?

https://travis-ci.org/plv8/plv8/jobs/495275461

**Comment by JerrySievert** [comment]
the build time is mostly v8 - which is ok to be cached.  the time increased significantly when spectre/meltdown mitigations were deployed for travis.

the build is a matrix, so old versions are a-ok.

**Comment by JerrySievert** [comment]
hm. this is failing for me.

existing copy of `build/v8` was deleted, and this occurred:

```
		rm -f /Users/jerry/work/plv8/build/autov8_fetched; echo Tue Feb 19 09:15:59 PST 2019 > /Users/jerry/work/plv8/build/autov8_fetched
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
```

after canceling the build, I tried to continue:

```
cd /Users/jerry/work/plv8/build/v8; git checkout 7.0.276.20 && \
		rm -f /Users/jerry/work/plv8/build/autov8_gitcheckedout; echo Tue Feb 19 09:17:36 PST 2019 > /Users/jerry/work/plv8/build/autov8_gitcheckedout
/bin/sh: line 0: cd: /Users/jerry/work/plv8/build/v8: No such file or directory
error: pathspec '7.0.276.20' did not match any file(s) known to git.
cd /Users/jerry/work/plv8/build/v8; gclient sync && \
		rm -f /Users/jerry/work/plv8/build/autov8_gclient_synced; echo Tue Feb 19 09:17:36 PST 2019 > /Users/jerry/work/plv8/build/autov8_gclient_synced
/bin/sh: line 0: cd: /Users/jerry/work/plv8/build/v8: No such file or directory
Error: client not configured; see 'gclient config'
cd /Users/jerry/work/plv8/build/v8/build/config; git cherry-pick 4287a0d364541583a50cc91465330251460d489a && \
		rm -f /Users/jerry/work/plv8/build/autov8_cherry_picked; echo Tue Feb 19 09:17:39 PST 2019 > /Users/jerry/work/plv8/build/autov8_cherry_picked
/bin/sh: line 0: cd: /Users/jerry/work/plv8/build/v8/build/config: No such file or directory
fatal: bad object 4287a0d364541583a50cc91465330251460d489a
rm -fr /Users/jerry/work/plv8/build/v8/out.gn
cd /Users/jerry/work/plv8/build/v8; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false && \
		rm -f /Users/jerry/work/plv8/build/autov8_v8gen; echo Tue Feb 19 09:17:39 PST 2019 > /Users/jerry/work/plv8/build/autov8_v8gen
/bin/sh: line 0: cd: /Users/jerry/work/plv8/build/v8: No such file or directory
/bin/sh: tools/dev/v8gen.py: No such file or directory
cd /Users/jerry/work/plv8/build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
/bin/sh: line 0: cd: /Users/jerry/work/plv8/build/v8: No such file or directory
ninja: Entering directory `out.gn/x64.release'
ninja: fatal: chdir to 'out.gn/x64.release' - No such file or directory
make: *** [v8] Error 1
```

having `build/v8` disappear would have been catastrophic for me (I'm on a metered satellite connection), thankfully I have backups; I think this needs to be addressed.  in addition, it doesn't seem to pick up after cancelation (see the error pasted).

**Comment by asah** [comment]
ah, this was intended for a fresh checkout - see linkedin msg for an idea
on how to workaround low bandwidth :-)

**Comment by JerrySievert** [comment]
`gclient` already has state management, in that it can detect and fix any broken state via `gclient sync`.  I think it would be better to work with that mechanism rather than against it.

I still feel that the best solution is to take the node.js route, and circumvent the build system completely, but there's a lot of work involved atm.

**Comment by asah** [comment]
ah, good call - I'm on it.

**Comment by JerrySievert** [comment]
note that circumventing the v8 build system would need to support windows as well - see the `windows` directory, and the documentation for an outline of the current state of building on windows (and that 3.0alpha currently fails due to build failures in windows)

**Comment by JerrySievert** [comment]
closing.

**Pull request closed without merging**
